name = "cf-proxyip-us"
main = "worker.js"
compatibility_date = "2026-05-27"
account_id = "87b45e88da4247bc07f9c9421c2eb2e9"
workers_dev = false
preview_urls = false

[observability]
enabled = true

[[kv_namespaces]]
binding = "PROXYIP_KV"
id = "4e593e914be0433994a2a1ddce6f5a07"
[vars]
PROXYIP_RECORD_NAME = "proxyip.cityfox.ccwu.cc"
